# Generated by Django 4.2.7 on 2023-11-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
